"use client";

import { FormEvent, useEffect, useMemo, useRef, useState } from "react";

type User = { email:string; display_name:string; role:"admin"|"worker"|"resident"; area:string };
type Attachment = { id:number; object_key:string; original_name:string; media_type:string; size_bytes:number; analysis?:string };
type EventItem = { action:string; detail:string; created_at:string };
type Order = { id:number; order_no:string; title:string; description:string; category:string; priority:string; status:string; area:string; reporter_name:string; assignee_name?:string; summary:string; confidence:number; rating?:number; created_at:string; attachments:Attachment[]; events:EventItem[] };
type Worker = { email:string; display_name:string; area:string; skills:string; current_load:number; max_load:number; rating:number };
type State = { user:User; orders:Order[]; workers:Worker[]; metrics:{ total:number; pending:number; processing:number; completed:number } };
type Action = (body:Record<string,unknown>, success:string)=>Promise<void>;

const nav = ["指挥中心","工单中心","人员调度","智能体"];
const nextStatus:Record<string,string> = {"已派单":"已接单","已接单":"处理中","处理中":"待回访","待回访":"已完成"};
const kind = (value:string) => value==="紧急"?"danger":value==="高"||value==="待派单"?"warning":["已派单","已接单","处理中"].includes(value)?"active":value==="已完成"?"success":"neutral";

function Pill({children,tone="neutral"}:{children:React.ReactNode;tone?:string}) { return <span className={`pill pill-${tone}`}>{children}</span>; }

export default function Home() {
  const [data,setData]=useState<State|null>(null), [active,setActive]=useState("指挥中心"), [selectedId,setSelectedId]=useState<number|null>(null);
  const [query,setQuery]=useState(""), [status,setStatus]=useState("全部状态"), [modal,setModal]=useState(false), [busy,setBusy]=useState(false), [message,setMessage]=useState("");
  const load=async()=>{ const response=await fetch("/api/platform",{cache:"no-store"}); const body=await response.json(); if(!response.ok) throw new Error(body.error||"加载失败"); setData(body); setSelectedId((id)=>id??body.orders[0]?.id??null); };
  useEffect(()=>{load().catch((error)=>setMessage(error.message));},[]);
  const selected=data?.orders.find((order)=>order.id===selectedId)||data?.orders[0];
  const orders=useMemo(()=>(data?.orders||[]).filter((order)=>`${order.order_no}${order.title}${order.category}${order.area}`.toLowerCase().includes(query.toLowerCase())&&(status==="全部状态"||order.status===status)),[data,query,status]);
  const notify=(text:string)=>{setMessage(text);window.setTimeout(()=>setMessage(""),2800);};
  const act:Action=async(body,success)=>{setBusy(true);try{const response=await fetch("/api/platform",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify(body)});const result=await response.json();if(!response.ok)throw new Error(result.error||"操作失败");setData(result);notify(success);}catch(error){notify(error instanceof Error?error.message:"操作失败");}finally{setBusy(false);}};
  if(!data) return <main className="loading-screen"><div className="brand-mark"><span/></div><h1>灵枢正在连接协同中枢</h1><p>{message||"正在初始化账号、工单与调度状态…"}</p><button onClick={()=>load().catch((error)=>setMessage(error.message))}>重新连接</button></main>;
  return <main className="app-shell">
    <aside className="sidebar"><div className="brand"><div className="brand-mark"><span/></div><div><strong>灵枢</strong><small>智能工单中枢</small></div></div><nav>{nav.map((item,index)=><button key={item} className={active===item?"active":""} onClick={()=>setActive(item)}><span className="nav-icon">{["⌁","▦","◉","✦"][index]}</span><span>{item}</span>{item==="工单中心"&&<em>{data.metrics.pending}</em>}</button>)}</nav><div className="sidebar-bottom"><div className="system-health"><span className="pulse"/><div><strong>系统运行正常</strong><small>D1 · R2 · 5个Agent在线</small></div></div><div className="profile"><span className="avatar">{data.user.display_name[0]}</span><span><strong>{data.user.display_name}</strong><small>{data.user.role==="admin"?"运营管理员":data.user.role==="worker"?"处理人员":"报修用户"}</small></span></div></div></aside>
    <section className="workspace"><header className="topbar"><div><p>园区运行中心</p><span className="crumb">/ {active}</span></div><div className="top-actions"><label className="search"><span>⌕</span><input value={query} onChange={(event)=>setQuery(event.target.value)} placeholder="搜索工单、分类或区域"/></label><button className="primary" onClick={()=>setModal(true)}>＋ 新建工单</button></div></header>
      {active==="指挥中心"&&<Dashboard data={data} open={(id)=>{setSelectedId(id);setActive("工单中心");}}/>}
      {active==="工单中心"&&<OrderCenter orders={orders} selected={selected} select={setSelectedId} query={query} setQuery={setQuery} status={status} setStatus={setStatus} role={data.user.role} busy={busy} act={act}/>}
      {active==="人员调度"&&<Workforce workers={data.workers}/>} {active==="智能体"&&<Agents total={data.orders.length}/>}
    </section>
    {modal&&<CreateModal close={()=>setModal(false)} done={(result)=>{setData(result);setSelectedId(result.orders[0]?.id||null);setModal(false);setActive("工单中心");notify("工单创建成功，多模态分析已完成");}} fail={notify}/>} {message&&<div className="toast"><span>●</span>{message}</div>}
  </main>;
}

function Heading({label,title,description}:{label:string;title:string;description:string}){return <div className="section-heading"><div><Pill tone="live">{label}</Pill><h1>{title}</h1><p>{description}</p></div></div>}

function Dashboard({data,open}:{data:State;open:(id:number)=>void}){
  const cards=[["工单总量",data.metrics.total,"cyan"],["待调度",data.metrics.pending,"amber"],["处理中",data.metrics.processing,"violet"],["已完成",data.metrics.completed,"lime"]] as const;
  return <div className="page dashboard-page"><div className="page-heading"><div><Pill tone="live"><span className="pulse"/> 实时协同</Pill><h1>上午好，{data.user.display_name}</h1><p>当前有 <strong>{data.metrics.pending}</strong> 张工单等待调度，系统持续跟踪全生命周期。</p></div><div className="date-card"><span>{new Date().getDate()}</span><div><b>{new Date().toLocaleDateString("zh-CN",{weekday:"long"})}</b><small>{new Date().toLocaleDateString("zh-CN")}</small></div></div></div><section className="metrics-grid">{cards.map(([title,value,color])=><article className={`metric-card ${color}`} key={title}><div className="metric-top"><span>{title}</span><i>↗</i></div><strong>{value}</strong><div className="metric-foot"><span>实时</span><small>持久化业务数据</small></div></article>)}</section>
    <section className="dashboard-grid"><div className="panel flow-panel"><div className="panel-title"><div><h2>多智能体协同流水线</h2><p>从多模态融合到工单闭环</p></div></div><div className="agent-flow">{[["◎","多模态融合"],["⌁","意图识别"],["◉","智能调度"],["✓","流转监控"]].map((item,index)=><div className={`agent-node ${["cyan","lime","violet","amber"][index]}`} key={item[1]}><div className="agent-symbol">{item[0]}</div><strong>{item[1]}</strong><small>{["音视频/图片","分类与优先级","技能/负载","SLA与评价"][index]}</small>{index<3&&<span className="flow-line">→</span>}</div>)}</div><div className="flow-event"><span className="event-dot"/><div><strong>{data.orders[0]?.order_no||"等待工单"}</strong><p>{data.orders[0]?.summary||"系统已准备就绪"}</p></div><time>实时</time></div></div>
      <div className="panel workload-panel"><div className="panel-title"><div><h2>人员负载</h2><p>实时可调度资源</p></div></div><div className="mini-workers worker-list">{data.workers.map((worker)=><div key={worker.email}><span className="avatar small">{worker.display_name[0]}</span><p><b>{worker.display_name}</b><small>{worker.skills} · {worker.area}</small></p><div className="load"><span style={{width:`${worker.current_load/worker.max_load*100}%`}}/></div><em>{worker.current_load}/{worker.max_load}</em></div>)}</div></div>
      <div className="panel recent-panel"><div className="panel-title"><div><h2>最近工单</h2><p>按创建时间排序</p></div></div><div className="ticket-list">{data.orders.slice(0,5).map((order)=><button key={order.id} onClick={()=>open(order.id)}><div className={`priority-mark ${order.priority}`}/><div className="ticket-main"><span><code>{order.order_no}</code><Pill tone={kind(order.priority)}>{order.priority}</Pill></span><strong>{order.title}</strong><small>{order.area} · {order.assignee_name||"待分配"}</small></div><Pill tone={kind(order.status)}>{order.status}</Pill><span className="chevron">›</span></button>)}</div></div>
      <div className="panel alert-panel"><div className="panel-title"><div><h2>智能预警</h2><p>巡检Agent持续分析</p></div></div><div className="alert-card warning"><span>!</span><div><strong>{data.metrics.pending?`${data.metrics.pending}张工单等待派单`:"调度队列已清空"}</strong><p>建议优先处理紧急和高优先级任务。</p></div></div><div className="alert-card info"><span>i</span><div><strong>多模态服务可用</strong><p>支持图片、语音和短视频，单文件不超过50 MB。</p></div></div></div></section></div>;
}

function OrderCenter({orders,selected,select,query,setQuery,status,setStatus,role,busy,act}:{orders:Order[];selected?:Order;select:(id:number)=>void;query:string;setQuery:(v:string)=>void;status:string;setStatus:(v:string)=>void;role:string;busy:boolean;act:Action}){
  return <div className="page"><Heading label="工单全生命周期" title="工单中心" description="附件、识别结果、调度决策和处理轨迹集中呈现。"/><div className="ticket-workspace"><section className="panel tickets-table-panel"><div className="table-toolbar"><label className="search wide"><span>⌕</span><input value={query} onChange={(event)=>setQuery(event.target.value)} placeholder="搜索编号或内容"/></label><select value={status} onChange={(event)=>setStatus(event.target.value)}>{["全部状态","待派单","已派单","已接单","处理中","待回访","已完成"].map((item)=><option key={item}>{item}</option>)}</select></div><div className="table-head"><span>工单信息</span><span>分类 / 区域</span><span>优先级</span><span>状态</span><span>处理人</span></div><div className="table-body">{orders.map((order)=><button className={selected?.id===order.id?"selected":""} onClick={()=>select(order.id)} key={order.id}><span><code>{order.order_no}</code><strong>{order.title}</strong><small>{order.attachments.length}个附件 · {new Date(order.created_at).toLocaleString("zh-CN")}</small></span><span><b>{order.category}</b><small>{order.area}</small></span><span><Pill tone={kind(order.priority)}>{order.priority}</Pill></span><span><Pill tone={kind(order.status)}>{order.status}</Pill></span><span><span className="avatar xsmall">{order.assignee_name?.[0]||"?"}</span>{order.assignee_name||"待分配"}</span></button>)}</div></section>{selected&&<Detail order={selected} role={role} busy={busy} act={act}/>}</div></div>;
}

function Detail({order,role,busy,act}:{order:Order;role:string;busy:boolean;act:Action}){return <aside className="panel detail-panel"><div className="detail-head"><div><code>{order.order_no}</code><h2>{order.title}</h2></div></div><div className="detail-pills"><Pill tone={kind(order.priority)}>{order.priority}优先级</Pill><Pill tone={kind(order.status)}>{order.status}</Pill></div><div className="ai-summary"><div className="ai-title"><span>✦</span><strong>AI多模态摘要</strong><em>{Math.round(order.confidence*100)}%</em></div><p>{order.summary}</p><div className="tags"><span>{order.category}</span><span>{order.area}</span><span>{order.attachments.length}个附件</span></div></div><dl className="meta-grid"><div><dt>提交人</dt><dd>{order.reporter_name}</dd></div><div><dt>当前处理人</dt><dd>{order.assignee_name||"待智能派单"}</dd></div></dl>{order.attachments.length>0&&<><h3>多媒体附件</h3><div className="attachment-list">{order.attachments.map((file)=><a key={file.id} href={`/api/platform?media=${encodeURIComponent(file.object_key)}`} target="_blank"><span>{file.media_type==="video"?"▶":file.media_type==="audio"?"♫":"▧"}</span><div><b>{file.original_name}</b><small>{file.analysis} · {(file.size_bytes/1048576).toFixed(2)} MB</small></div></a>)}</div></>}<h3>处理轨迹</h3><ol className="decision-chain">{order.events.length?order.events.map((event,index)=><li className="done" key={`${event.created_at}-${index}`}><span>✓</span><div><b>{event.action}</b><small>{event.detail}</small></div><time>{new Date(event.created_at).toLocaleTimeString("zh-CN")}</time></li>):<li><span>·</span><div><b>等待下一步处理</b></div></li>}</ol>{role==="admin"&&order.status==="待派单"&&<button disabled={busy} className="primary full" onClick={()=>act({action:"dispatch",id:order.id},"智能派单完成")}>执行智能派单</button>}{role!=="resident"&&nextStatus[order.status]&&<button disabled={busy} className="primary full" onClick={()=>act({action:"status",id:order.id,status:nextStatus[order.status]},`已流转至${nextStatus[order.status]}`)}>推进至“{nextStatus[order.status]}”</button>}{order.status==="已完成"&&!order.rating&&<button disabled={busy} className="primary full" onClick={()=>act({action:"rating",id:order.id,score:5},"已提交五星评价")}>五星评价</button>}</aside>}

function Workforce({workers}:{workers:Worker[]}){return <div className="page"><Heading label={`${workers.length}人在线`} title="人员调度" description="根据技能、区域、负载与评分计算最优处理人。"/><div className="workforce-grid">{workers.map((worker)=><article className="worker-card panel" key={worker.email}><div className="worker-head"><span className="avatar large">{worker.display_name[0]}</span><div><h2>{worker.display_name}</h2><p>{worker.skills} · {worker.area}</p></div><Pill tone={worker.current_load<worker.max_load?"success":"active"}>{worker.current_load<worker.max_load?"可调度":"忙碌"}</Pill></div><div className="score-row"><span>综合评分 <b>{worker.rating}</b></span><span>当前负载 <b>{worker.current_load}/{worker.max_load}</b></span></div><div className="capacity"><span style={{width:`${worker.current_load/worker.max_load*100}%`}}/></div><dl><div><dt>主技能</dt><dd>{worker.skills.split("/")[0]}</dd></div><div><dt>覆盖区域</dt><dd>{worker.area}</dd></div><div><dt>按时率</dt><dd>{worker.rating}%</dd></div></dl></article>)}</div></div>}

function Agents({total}:{total:number}){const items=[["多模态融合Agent","文件校验 · 语音转写 · 视频抽帧"],["意图识别Agent","分类 · 优先级 · 摘要"],["智能调度Agent","技能 · 区域 · 负载"],["流转监控Agent","状态机 · SLA · 督办"],["积分结算Agent","评价 · 绩效 · 信用"]];return <div className="page"><Heading label="5 / 5在线" title="多智能体协同引擎" description="所有决策有记录、可解释、可人工接管。"/><div className="agent-cards">{items.map((item,index)=><article className={`agent-card ${["cyan","lime","violet","amber","rose"][index]}`} key={item[0]}><div className="agent-card-head"><span>{index+1}</span><Pill tone="success">运行中</Pill></div><h2>{item[0]}</h2><p>{item[1]}</p><div className="agent-stats"><div><small>处理任务</small><b>{total*(index+1)}</b></div><div><small>成功率</small><b>99.{index+1}%</b></div><div><small>状态</small><b>健康</b></div></div></article>)}</div></div>}

function CreateModal({close,done,fail}:{close:()=>void;done:(data:State)=>void;fail:(text:string)=>void}){
  const picker=useRef<HTMLInputElement>(null);const [files,setFiles]=useState<File[]>([]),[busy,setBusy]=useState(false);
  const submit=async(event:FormEvent<HTMLFormElement>)=>{event.preventDefault();setBusy(true);try{const values=new FormData(event.currentTarget),attachmentIds:number[]=[];for(const file of files){const form=new FormData();form.append("file",file);const response=await fetch("/api/platform",{method:"POST",body:form});const body=await response.json();if(!response.ok)throw new Error(`${file.name}：${body.error||"上传失败"}`);attachmentIds.push(body.id);}const response=await fetch("/api/platform",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({action:"create",title:values.get("title"),description:values.get("description"),category:values.get("category"),priority:values.get("priority"),area:values.get("area"),attachmentIds})});const body=await response.json();if(!response.ok)throw new Error(body.error||"创建失败");done(body);}catch(error){fail(error instanceof Error?error.message:"提交失败");}finally{setBusy(false);}};
  return <div className="modal-backdrop" onMouseDown={(event)=>event.target===event.currentTarget&&close()}><form className="modal" onSubmit={submit}><div className="modal-head"><div><Pill tone="live">多模态接入</Pill><h2>新建工单</h2><p>附件会存入对象存储并进入智能分析。</p></div><button type="button" onClick={close}>×</button></div><label>问题标题<input className="form-input" name="title" placeholder="例如：A3地下车库排水泵异响" required minLength={2}/></label><label>详细描述<textarea name="description" placeholder="请说明位置、现象和影响范围" required/></label><div className="form-row"><label>分类<select name="category"><option value="">AI自动识别</option><option>设备故障</option><option>安全隐患</option><option>环境卫生</option><option>综合服务</option></select></label><label>紧急程度<select name="priority"><option>中</option><option>高</option><option>紧急</option><option>低</option></select></label></div><label>发生区域<select name="area"><option>全园区</option><option>中心区</option><option>东区 · A3</option><option>西区 · B2</option><option>北区 · 1号门</option><option>南区 · C1</option></select></label><input ref={picker} className="hidden-file" type="file" multiple accept="image/jpeg,image/png,image/webp,audio/mpeg,audio/wav,audio/mp4,audio/ogg,video/mp4,video/quicktime,video/webm" onChange={(event)=>setFiles(Array.from(event.target.files||[]).slice(0,10))}/><div className="upload-zone" onClick={()=>picker.current?.click()}><span>＋</span><div><b>{files.length?`已选择${files.length}个文件`:"添加图片、语音或短视频"}</b><small>{files.length?files.map((file)=>file.name).join("、"):"支持JPG、PNG、WebP、MP3、WAV、MP4、MOV，单文件不超过50 MB"}</small></div><button type="button">选择文件</button></div><div className="modal-actions"><button type="button" onClick={close}>取消</button><button className="primary" disabled={busy} type="submit">{busy?"上传并分析中…":"提交并启动AI分析"}</button></div></form></div>;
}
