"use client";

import { FormEvent, useEffect, useMemo, useRef, useState } from "react";

type User = { email:string; authenticated_email?:string; display_name:string; role:"admin"|"worker"|"resident"; actual_role?:"admin"|"worker"|"resident"; area:string };
type Attachment = { id:number; object_key:string; original_name:string; media_type:string; size_bytes:number; analysis?:string };
type EventItem = { action:string; detail:string; created_at:string };
type Order = { id:number; order_no:string; title:string; description:string; category:string; priority:string; status:string; area:string; reporter_name:string; assignee_name?:string; summary:string; confidence:number; rating?:number; created_at:string; attachments:Attachment[]; events:EventItem[] };
type Worker = { email:string; display_name:string; area:string; skills:string; current_load:number; max_load:number; rating:number };
type Performance = { credit_points:number; completed_orders:number; on_time_rate:number; satisfaction:number; updated_at:string };
type OpsHealth = { human_review_pending:number; patrol_alerts:string[]; backlog_count:number; worker_utilization:number; agent_checks:Record<string,string>; persisted:Record<string,unknown> };
type State = { user:User; canSwitchRole:boolean; orders:Order[]; workers:Worker[]; metrics:{ total:number; pending:number; human_review:number; processing:number; completed:number }; performance:Performance|null; opsHealth:OpsHealth };
type Action = (body:Record<string,unknown>, success:string)=>Promise<void>;
type UploadMode = "all"|"image"|"audio"|"video"|"text";

const roleNav = {
  admin: [{key:"指挥中心",label:"指挥中心",icon:"⌁"},{key:"工单中心",label:"工单中心",icon:"▦"},{key:"人审队列",label:"人审队列",icon:"◎"},{key:"人员调度",label:"人员调度",icon:"◉"},{key:"智能体",label:"智能体",icon:"✦"}],
  worker: [{key:"我的任务",label:"我的任务",icon:"▦"},{key:"积分绩效",label:"积分绩效",icon:"✦"}],
  resident: [{key:"报修服务",label:"维修上传",icon:"＋"},{key:"服务评价",label:"服务评价",icon:"☆"}],
} as const;
const nextStatus:Record<string,string> = {"已派单":"已接单","已接单":"处理中","处理中":"待回访","待回访":"已完成"};
const kind = (value:string) => value==="紧急"?"danger":value==="高"||value==="待派单"?"warning":value==="待人审"?"active":["已派单","已接单","处理中"].includes(value)?"active":value==="已完成"?"success":"neutral";

function Pill({children,tone="neutral"}:{children:React.ReactNode;tone?:string}) { return <span className={`pill pill-${tone}`}>{children}</span>; }

export default function Home() {
  const [data,setData]=useState<State|null>(null), [active,setActive]=useState("指挥中心"), [selectedId,setSelectedId]=useState<number|null>(null);
  const [query,setQuery]=useState(""), [status,setStatus]=useState("全部状态"), [modal,setModal]=useState(false), [modalMode,setModalMode]=useState<UploadMode>("all"), [busy,setBusy]=useState(false), [message,setMessage]=useState(""), [viewRole,setViewRole]=useState<string|null>(null);
  const load=async(role?:string|null)=>{ const headers:Record<string,string>={}; if(role)headers["x-workorder-role"]=role; const response=await fetch("/api/platform",{cache:"no-store",headers}); const body=await response.json(); if(!response.ok) throw new Error(body.error||"加载失败"); setData(body); setSelectedId(body.orders[0]?.id??null); return body as State; };
  useEffect(()=>{load().catch((error)=>setMessage(error.message));},[]);
  const selected=data?.orders.find((order)=>order.id===selectedId)||data?.orders[0];
  const orders=useMemo(()=>(data?.orders||[]).filter((order)=>`${order.order_no}${order.title}${order.category}${order.area}`.toLowerCase().includes(query.toLowerCase())&&(status==="全部状态"||order.status===status)),[data,query,status]);
  const notify=(text:string)=>{setMessage(text);window.setTimeout(()=>setMessage(""),2800);};
  const act:Action=async(body,success)=>{setBusy(true);try{const headers:Record<string,string>={"content-type":"application/json"};if(viewRole)headers["x-workorder-role"]=viewRole;const response=await fetch("/api/platform",{method:"POST",headers,body:JSON.stringify(body)});const result=await response.json();if(!response.ok)throw new Error(result.error||"操作失败");setData(result);notify(success);}catch(error){notify(error instanceof Error?error.message:"操作失败");}finally{setBusy(false);}};
  if(!data) return <main className="loading-screen"><div className="brand-mark"><span/></div><h1>灵枢正在连接协同中枢</h1><p>{message||"正在初始化账号、工单与调度状态…"}</p><button onClick={()=>load().catch((error)=>setMessage(error.message))}>重新连接</button></main>;
  if(!viewRole) return <RoleLogin data={data} select={async(role)=>{setBusy(true);try{await load(role);setViewRole(role);setActive(role==="resident"?"报修服务":role==="worker"?"我的任务":"指挥中心");setQuery("");setStatus("全部状态");}catch(error){setMessage(error instanceof Error?error.message:"身份切换失败");}finally{setBusy(false);}}} busy={busy} message={message}/>;
  const menu=roleNav[data.user.role]; const currentLabel=menu.find((item)=>item.key===active)?.label||active;
  return <main className="app-shell">
    <aside className="sidebar"><div className="brand"><div className="brand-mark"><span/></div><div><strong>灵枢</strong><small>智能工单中枢</small></div></div><nav>{menu.map((item)=><button key={item.key} className={active===item.key?"active":""} onClick={()=>setActive(item.key)}><span className="nav-icon">{item.icon}</span><span>{item.label}</span>{item.key==="工单中心"&&<em>{data.metrics.pending}</em>}{item.key==="人审队列"&&data.metrics.human_review>0&&<em>{data.metrics.human_review}</em>}</button>)}</nav><div className="sidebar-bottom"><div className="system-health"><span className="pulse"/><div><strong>{data.opsHealth?.patrol_alerts?.length?`巡检 ${data.opsHealth.patrol_alerts.length} 条告警`:"系统运行正常"}</strong><small>Work-Order Agent · 工具层在线</small></div></div><div className="profile"><span className="avatar">{data.user.display_name[0]}</span><span><strong>{data.user.display_name}</strong><small>{data.user.role==="admin"?"运营管理员":data.user.role==="worker"?"处理人员":"居民用户"}</small></span></div><button className="role-switch" onClick={()=>setViewRole(null)}>⇄ 切换身份</button></div></aside>
    <section className="workspace"><header className="topbar"><div><p>{data.user.role==="resident"?"居民服务中心":data.user.role==="worker"?"现场工作中心":"园区运行中心"}</p><span className="crumb">/ {currentLabel}</span></div><div className="top-actions">{data.user.role!=="resident"&&<label className="search"><span>⌕</span><input value={query} onChange={(event)=>setQuery(event.target.value)} placeholder="搜索任务、分类或区域"/></label>}{data.user.role==="resident"&&active==="报修服务"&&<button className="primary" onClick={()=>{setModalMode("all");setModal(true);}}>＋ 上传维修</button>}{data.user.role==="admin"&&<button className="primary" onClick={()=>{setModalMode("all");setModal(true);}}>＋ 新建工单</button>}</div></header>
      {data.user.role==="resident"&&active==="报修服务"&&<ResidentDashboard create={(mode)=>{setModalMode(mode);setModal(true);}}/>}
      {data.user.role==="resident"&&active==="服务评价"&&<ResidentEvaluation orders={data.orders} busy={busy} act={act}/>}
      {data.user.role==="worker"&&active==="我的任务"&&<OrderCenter orders={orders} selected={selected} select={setSelectedId} query={query} setQuery={setQuery} status={status} setStatus={setStatus} role={data.user.role} busy={busy} act={act}/>}
      {data.user.role==="worker"&&active==="积分绩效"&&<WorkerPerformance data={data}/>}
      {data.user.role==="admin"&&active==="指挥中心"&&<Dashboard data={data} open={(id)=>{setSelectedId(id);setActive("工单中心");}}/>}
      {data.user.role==="admin"&&active==="工单中心"&&<OrderCenter orders={orders} selected={selected} select={setSelectedId} query={query} setQuery={setQuery} status={status} setStatus={setStatus} role={data.user.role} busy={busy} act={act}/>}
      {data.user.role==="admin"&&active==="人审队列"&&<HumanReviewCenter orders={data.orders.filter((order)=>order.status==="待人审")} busy={busy} act={act} open={(id)=>{setSelectedId(id);setActive("工单中心");}}/>}
      {data.user.role==="admin"&&active==="人员调度"&&<Workforce workers={data.workers}/>} {data.user.role==="admin"&&active==="智能体"&&<Agents ops={data.opsHealth} total={data.orders.length}/>}
    </section>
    {modal&&<CreateModal role={viewRole} mode={modalMode} close={()=>setModal(false)} done={(result)=>{setData(result);setSelectedId(result.orders[0]?.id||null);setModal(false);setActive(data.user.role==="resident"?"报修服务":"工单中心");notify("维修申请已提交，多模态分析完成");}} fail={notify}/>} {message&&<div className="toast"><span>●</span>{message}</div>}
  </main>;
}

function RoleLogin({data,select,busy,message}:{data:State;select:(role:"resident"|"worker"|"admin")=>void;busy:boolean;message:string}){
  const actual=data.user.actual_role||data.user.role;
  const roles=[
    {id:"resident" as const,icon:"⌂",title:"居民用户",subtitle:"维修上传与服务评价",description:"通过图片、语音、视频或文字上传维修问题，并对已完成服务进行评价。",features:["维修上传","多媒体采集","服务评价"]},
    {id:"worker" as const,icon:"⚒",title:"工作人员",subtitle:"任务处理与绩效成长",description:"处理智能调度分配给你的现场任务，查看个人积分与服务绩效。",features:["我的任务","状态流转","积分绩效"]},
    {id:"admin" as const,icon:"⌁",title:"运营管理员",subtitle:"全局指挥调度",description:"查看全局工单、人员负载与智能体状态，执行智能派单。",features:["指挥中心","人员调度","全局数据"]},
  ].filter((role)=>actual==="admin"||role.id===actual);
  return <main className="role-login"><section className="login-brand"><div className="brand-mark"><span/></div><div><strong>灵枢</strong><small>多模态智能工单协同调度平台</small></div></section><section className="role-panel"><Pill tone="live"><span className="pulse"/> 已完成安全身份认证</Pill><h1>选择您的工作身份</h1><p className="role-lead">当前登录账号：{data.user.authenticated_email||data.user.email}。系统会按所选身份加载专属工作台、数据范围与操作权限。</p><div className="role-grid">{roles.map((role)=><button className={`role-card role-${role.id}`} disabled={busy} key={role.id} onClick={()=>select(role.id)}><span className="role-icon">{role.icon}</span><div className="role-name"><h2>{role.title}</h2><small>{role.subtitle}</small></div><p>{role.description}</p><div className="role-features">{role.features.map((item)=><span key={item}>✓ {item}</span>)}</div><b>进入{role.title}工作台 <span>→</span></b></button>)}</div>{actual==="admin"&&<div className="role-hint"><span>i</span><p><strong>管理员演示模式</strong> 你可以随时从左侧“切换身份”返回此页面，体验三类用户的差异化权限。</p></div>}{message&&<div className="login-error">{message}</div>}<footer>身份权限由服务端验证 · 操作全程记录审计轨迹</footer></section></main>;
}

function Heading({label,title,description}:{label:string;title:string;description:string}){return <div className="section-heading"><div><Pill tone="live">{label}</Pill><h1>{title}</h1><p>{description}</p></div></div>}

function ResidentDashboard({create}:{create:(mode:UploadMode)=>void}){
  const actions=[
    {mode:"image" as const,icon:"▧",title:"图片报修",detail:"拍照或选择现场图片",format:"JPG · PNG · WebP",tone:"photo"},
    {mode:"audio" as const,icon:"♫",title:"语音报修",detail:"录音或上传语音说明",format:"MP3 · WAV · M4A",tone:"voice"},
    {mode:"video" as const,icon:"▶",title:"视频报修",detail:"拍摄或上传现场视频",format:"MP4 · MOV · WebM",tone:"video"},
    {mode:"text" as const,icon:"T",title:"文字报修",detail:"直接填写问题和位置",format:"快速提交",tone:"text"},
  ];
  return <div className="page resident-page"><section className="resident-hero"><div className="resident-copy"><Pill tone="live"><span className="pulse"/> 7×24小时在线受理</Pill><h1>遇到问题，随手报修</h1><p>选择一种最方便的方式告诉我们。图片、语音和视频会由AI自动识别问题类型与紧急程度。</p><div className="resident-trust"><span>✓ 单文件不超过50 MB</span><span>✓ 自动保存处理进度</span><span>✓ 全流程消息可追踪</span></div></div><div className="resident-visual"><div className="scan-ring"><span>✦</span></div><b>多模态AI识别</b><small>平均数秒完成初步分析</small></div></section>
    <section className="report-section"><div className="report-heading"><div><h2>请选择报修方式</h2><p>支持手机拍摄、录音，也可以从设备中选择已有文件</p></div><button onClick={()=>create("all")}>组合上传多个附件 →</button></div><div className="report-actions">{actions.map((action)=><button className={`report-action ${action.tone}`} key={action.mode} onClick={()=>create(action.mode)}><span className="report-icon">{action.icon}</span><div><h3>{action.title}</h3><p>{action.detail}</p><small>{action.format}</small></div><b>→</b></button>)}</div></section>
  </div>;
}

function ResidentEvaluation({orders,busy,act}:{orders:Order[];busy:boolean;act:Action}){
  const completed=orders.filter((order)=>order.status==="已完成");
  return <div className="page evaluation-page"><Heading label="服务完成后可评价" title="服务评价" description="对已经完成的维修服务进行评分，帮助我们持续提升服务质量。"/>{completed.length===0?<section className="panel empty-state"><span>☆</span><h2>暂无可评价的服务</h2><p>维修服务完成后会自动显示在这里。</p></section>:<section className="evaluation-grid">{completed.map((order)=><article className="panel evaluation-card" key={order.id}><div className="evaluation-head"><span className="service-icon">✓</span><div><h2>{order.title}</h2><p>{order.category} · {order.area}</p></div><Pill tone={order.rating?"success":"warning"}>{order.rating?"已评价":"待评价"}</Pill></div><dl><div><dt>服务人员</dt><dd>{order.assignee_name||"服务团队"}</dd></div><div><dt>完成时间</dt><dd>{new Date(order.created_at).toLocaleDateString("zh-CN")}</dd></div></dl>{order.rating?<div className="rated-result"><span>{"★".repeat(order.rating)}{"☆".repeat(5-order.rating)}</span><b>{order.rating}.0 分</b></div>:<div className="rating-area"><p>请为本次维修服务评分</p><div className="rating-stars">{[1,2,3,4,5].map((score)=><button disabled={busy} key={score} title={`${score}星`} onClick={()=>act({action:"rating",id:order.id,score},`已提交${score}星评价`)}>★<small>{score}</small></button>)}</div></div>}</article>)}</section>}</div>;
}

function WorkerPerformance({data}:{data:State}){
  const performance=data.performance||{credit_points:1000,completed_orders:0,on_time_rate:98,satisfaction:4.8,updated_at:new Date().toISOString()};
  const worker=data.workers.find((item)=>item.email===data.user.email);
  const completed=data.orders.filter((order)=>order.status==="已完成");
  const level=performance.credit_points>=1500?"金牌服务之星":performance.credit_points>=1100?"银牌服务之星":"成长服务之星";
  return <div className="page performance-page"><Heading label="个人服务档案" title="积分绩效" description="积分随任务完成和居民评价实时更新，记录每一次可靠服务。"/><section className="points-hero"><div><Pill tone="live">本月积分</Pill><strong>{performance.credit_points}</strong><p>{level} · 距离下一等级还需 {Math.max(0,1500-performance.credit_points)} 分</p></div><div className="points-ring"><span>{Math.min(100,Math.round(performance.credit_points/15))}%</span><small>成长进度</small></div></section><section className="performance-metrics"><article className="panel"><span>累计完成任务</span><strong>{performance.completed_orders}</strong><small>每完成一项 +10积分</small></article><article className="panel"><span>按时完成率</span><strong>{performance.on_time_rate}%</strong><small>保持稳定履约</small></article><article className="panel"><span>居民满意度</span><strong>{performance.satisfaction.toFixed(1)}</strong><small>满分 5.0</small></article><article className="panel"><span>当前任务负载</span><strong>{worker?`${worker.current_load}/${worker.max_load}`:"0/5"}</strong><small>系统智能均衡派单</small></article></section><section className="performance-bottom"><div className="panel score-rules"><div className="panel-title"><div><h2>积分规则</h2><p>清晰透明的成长机制</p></div></div>{[["按时完成维修任务","+10"],["获得居民五星评价","+5"],["协助处理紧急任务","+8"],["任务超时或退回","-5"]].map(([name,score])=><div className="score-rule" key={name}><span>{name}</span><b className={score.startsWith("+")?"positive":"negative"}>{score}</b></div>)}</div><div className="panel performance-history"><div className="panel-title"><div><h2>近期服务成果</h2><p>只展示你的已完成任务</p></div></div>{completed.length?<div className="result-list">{completed.slice(0,5).map((order)=><div key={order.id}><span className="result-check">✓</span><p><b>{order.title}</b><small>{order.area} · {order.category}</small></p><em>+10</em></div>)}</div>:<div className="mini-empty">完成首个任务后，绩效记录会显示在这里。</div>}</div></section></div>;
}

function Dashboard({data,open}:{data:State;open:(id:number)=>void}){
  const cards=[["工单总量",data.metrics.total,"cyan"],["待调度",data.metrics.pending,"amber"],["待人审",data.metrics.human_review,"violet"],["处理中",data.metrics.processing,"violet"],["已完成",data.metrics.completed,"lime"]] as const;
  const alerts=data.opsHealth?.patrol_alerts||[];
  return <div className="page dashboard-page"><div className="page-heading"><div><Pill tone="live"><span className="pulse"/> 实时协同</Pill><h1>上午好，{data.user.display_name}</h1><p>待调度 <strong>{data.metrics.pending}</strong> · 待人审 <strong>{data.metrics.human_review}</strong></p></div><div className="date-card"><span>{new Date().getDate()}</span><div><b>{new Date().toLocaleDateString("zh-CN",{weekday:"long"})}</b><small>{new Date().toLocaleDateString("zh-CN")}</small></div></div></div><section className="metrics-grid">{cards.map(([title,value,color])=><article className={`metric-card ${color}`} key={title}><div className="metric-top"><span>{title}</span><i>↗</i></div><strong>{value}</strong><div className="metric-foot"><span>实时</span><small>持久化业务数据</small></div></article>)}</section>
    <section className="dashboard-grid"><div className="panel flow-panel"><div className="panel-title"><div><h2>工单决策流水线</h2><p>多模态融合 → 单 Agent 按阶段决策</p></div></div><div className="agent-flow">{[["◎","多模态融合"],["✦","Work-Order Agent"],["◉","智能派单"],["✓","流转闭环"]].map((item,index)=><div className={`agent-node ${["cyan","lime","violet","amber"][index]}`} key={item[1]}><div className="agent-symbol">{item[0]}</div><strong>{item[1]}</strong><small>{["evidence 列表","建单识别 / 派单选人","加权打分","状态机+人审"][index]}</small>{index<3&&<span className="flow-line">→</span>}</div>)}</div><div className="flow-event"><span className="event-dot"/><div><strong>{data.orders[0]?.order_no||"等待工单"}</strong><p>{data.orders[0]?.summary||"系统已准备就绪"}</p></div><time>实时</time></div></div>
      <div className="panel workload-panel"><div className="panel-title"><div><h2>人员负载</h2><p>实时可调度资源</p></div></div><div className="mini-workers worker-list">{data.workers.map((worker)=><div key={worker.email}><span className="avatar small">{worker.display_name[0]}</span><p><b>{worker.display_name}</b><small>{worker.skills} · {worker.area}</small></p><div className="load"><span style={{width:`${worker.current_load/worker.max_load*100}%`}}/></div><em>{worker.current_load}/{worker.max_load}</em></div>)}</div></div>
      <div className="panel recent-panel"><div className="panel-title"><div><h2>最近工单</h2><p>按创建时间排序</p></div></div><div className="ticket-list">{data.orders.slice(0,5).map((order)=><button key={order.id} onClick={()=>open(order.id)}><div className={`priority-mark ${order.priority}`}/><div className="ticket-main"><span><code>{order.order_no}</code><Pill tone={kind(order.priority)}>{order.priority}</Pill></span><strong>{order.title}</strong><small>{order.area} · {order.assignee_name||"待分配"}</small></div><Pill tone={kind(order.status)}>{order.status}</Pill><span className="chevron">›</span></button>)}</div></div>
      <div className="panel alert-panel"><div className="panel-title"><div><h2>巡检与 Agent 健康</h2><p>积压 {data.opsHealth?.backlog_count ?? 0} · 负载 {Math.round((data.opsHealth?.worker_utilization ?? 0)*100)}%</p></div></div>{alerts.length?alerts.map((alert)=><div className="alert-card warning" key={alert}><span>!</span><div><strong>{alert}</strong></div></div>):<div className="alert-card info"><span>i</span><div><strong>巡检正常</strong><p>未发现超阈值积压或负载告警。</p></div></div>}</div></section></div>;
}

function OrderCenter({orders,selected,select,query,setQuery,status,setStatus,role,busy,act}:{orders:Order[];selected?:Order;select:(id:number)=>void;query:string;setQuery:(v:string)=>void;status:string;setStatus:(v:string)=>void;role:string;busy:boolean;act:Action}){
  const worker=role==="worker";
  return <div className="page"><Heading label={worker?"现场任务处理":"工单全生命周期"} title={worker?"我的任务":"工单中心"} description={worker?"这里只显示智能调度分配给你的任务，可接单并更新现场处理状态。":"附件、识别结果、调度决策和处理轨迹集中呈现。"}/><div className="ticket-workspace"><section className="panel tickets-table-panel"><div className="table-toolbar"><label className="search wide"><span>⌕</span><input value={query} onChange={(event)=>setQuery(event.target.value)} placeholder={worker?"搜索我的任务":"搜索编号或内容"}/></label><select value={status} onChange={(event)=>setStatus(event.target.value)}>{["全部状态","待人审","待派单","已派单","已接单","处理中","待回访","已完成"].map((item)=><option key={item}>{item}</option>)}</select></div><div className="table-head"><span>{worker?"任务信息":"工单信息"}</span><span>分类 / 区域</span><span>优先级</span><span>状态</span><span>处理人</span></div><div className="table-body">{orders.map((order)=><button className={selected?.id===order.id?"selected":""} onClick={()=>select(order.id)} key={order.id}><span><code>{order.order_no}</code><strong>{order.title}</strong><small>{order.attachments.length}个附件 · {new Date(order.created_at).toLocaleString("zh-CN")}</small></span><span><b>{order.category}</b><small>{order.area}</small></span><span><Pill tone={kind(order.priority)}>{order.priority}</Pill></span><span><Pill tone={kind(order.status)}>{order.status}</Pill></span><span><span className="avatar xsmall">{order.assignee_name?.[0]||"?"}</span>{order.assignee_name||"待分配"}</span></button>)}</div></section>{selected&&<Detail order={selected} role={role} busy={busy} act={act}/>}</div></div>;
}

function Detail({order,role,busy,act}:{order:Order;role:string;busy:boolean;act:Action}){return <aside className="panel detail-panel"><div className="detail-head"><div><code>{order.order_no}</code><h2>{order.title}</h2></div></div><div className="detail-pills"><Pill tone={kind(order.priority)}>{order.priority}优先级</Pill><Pill tone={kind(order.status)}>{order.status}</Pill></div><div className="ai-summary"><div className="ai-title"><span>✦</span><strong>AI多模态摘要</strong><em>{Math.round(order.confidence*100)}%</em></div><p>{order.summary}</p><div className="tags"><span>{order.category}</span><span>{order.area}</span><span>{order.attachments.length}个附件</span></div></div><dl className="meta-grid"><div><dt>提交人</dt><dd>{order.reporter_name}</dd></div><div><dt>当前处理人</dt><dd>{order.assignee_name||"待智能派单"}</dd></div></dl>{order.attachments.length>0&&<><h3>多媒体附件</h3><div className="attachment-list">{order.attachments.map((file)=><a key={file.id} href={`/api/platform?media=${encodeURIComponent(file.object_key)}`} target="_blank"><span>{file.media_type==="video"?"▶":file.media_type==="audio"?"♫":"▧"}</span><div><b>{file.original_name}</b><small>{file.analysis} · {(file.size_bytes/1048576).toFixed(2)} MB</small></div></a>)}</div></>}<h3>处理轨迹</h3><ol className="decision-chain">{order.events.length?order.events.map((event,index)=><li className="done" key={`${event.created_at}-${index}`}><span>{event.action.includes("conflict")||event.action.includes("human")?"◎":"✓"}</span><div><b>{event.action}</b><small>{event.detail}</small></div><time>{new Date(event.created_at).toLocaleTimeString("zh-CN")}</time></li>):<li><span>·</span><div><b>等待下一步处理</b></div></li>}</ol>{role==="admin"&&order.status==="待人审"&&<HumanReviewForm order={order} busy={busy} act={act}/>}{role==="admin"&&order.status==="待派单"&&<button disabled={busy} className="primary full" onClick={()=>act({action:"dispatch",id:order.id},"智能派单完成")}>执行智能派单</button>}{role!=="resident"&&nextStatus[order.status]&&<button disabled={busy} className="primary full" onClick={()=>act({action:"status",id:order.id,status:nextStatus[order.status]},`已流转至${nextStatus[order.status]}`)}>推进至“{nextStatus[order.status]}”</button>}{role==="resident"&&order.status==="已完成"&&!order.rating&&<button disabled={busy} className="primary full" onClick={()=>act({action:"rating",id:order.id,score:5},"已提交五星评价")}>五星评价</button>}</aside>}

function HumanReviewForm({order,busy,act}:{order:Order;busy:boolean;act:Action}){
  const [category,setCategory]=useState(order.category);
  const [priority,setPriority]=useState(order.priority);
  return <div className="human-review-box"><h3>人工审核</h3><p>置信度 {Math.round(order.confidence*100)}% 低于阈值，请确认分类后再派单。</p><div className="form-row"><label>分类<select value={category} onChange={(e)=>setCategory(e.target.value)}><option>暖通空调</option><option>设备故障</option><option>照明设施</option><option>安全隐患</option><option>环境卫生</option><option>综合服务</option></select></label><label>优先级<select value={priority} onChange={(e)=>setPriority(e.target.value)}><option>紧急</option><option>高</option><option>中</option></select></label></div><button disabled={busy} className="primary full" onClick={()=>act({action:"human_review",id:order.id,category,priority,note:"管理端确认"},"人工审核完成")}>确认分类并放行派单</button></div>;
}

function HumanReviewCenter({orders,busy,act,open}:{orders:Order[];busy:boolean;act:Action;open:(id:number)=>void}){
  return <div className="page"><Heading label={`${orders.length} 待审`} title="人审队列" description="低置信度或冲突工单在此确认，确认后状态变为待派单。"/>{orders.length===0?<section className="panel empty-state"><span>◎</span><h2>暂无待审工单</h2><p>新工单若置信度不足会自动进入此队列。</p></section>:<section className="evaluation-grid">{orders.map((order)=><article className="panel evaluation-card" key={order.id}><div className="evaluation-head"><div><h2>{order.title}</h2><p>{order.order_no} · {order.area}</p></div><Pill tone="active">待人审</Pill></div><p>{order.summary}</p><div className="form-row"><button disabled={busy} className="primary" onClick={()=>act({action:"human_review",id:order.id,category:order.category,priority:order.priority,note:"队列快速确认"},"人工审核完成")}>确认 {order.category}</button><button onClick={()=>open(order.id)}>查看详情</button></div></article>)}</section>}</div>;
}

function Workforce({workers}:{workers:Worker[]}){return <div className="page"><Heading label={`${workers.length}人在线`} title="人员调度" description="根据技能、区域、负载与评分计算最优处理人。"/><div className="workforce-grid">{workers.map((worker)=><article className="worker-card panel" key={worker.email}><div className="worker-head"><span className="avatar large">{worker.display_name[0]}</span><div><h2>{worker.display_name}</h2><p>{worker.skills} · {worker.area}</p></div><Pill tone={worker.current_load<worker.max_load?"success":"active"}>{worker.current_load<worker.max_load?"可调度":"忙碌"}</Pill></div><div className="score-row"><span>综合评分 <b>{worker.rating}</b></span><span>当前负载 <b>{worker.current_load}/{worker.max_load}</b></span></div><div className="capacity"><span style={{width:`${worker.current_load/worker.max_load*100}%`}}/></div><dl><div><dt>主技能</dt><dd>{worker.skills.split("/")[0]}</dd></div><div><dt>覆盖区域</dt><dd>{worker.area}</dd></div><div><dt>按时率</dt><dd>{worker.rating}%</dd></div></dl></article>)}</div></div>}

function Agents({ops,total}:{ops:OpsHealth;total:number}){
  const tools=["流转状态机","积分结算","巡检指标","Watchdog 探活"];
  const status=ops?.agent_checks?.work_order||"llm+rules / scoring";
  return <div className="page"><Heading label="1 决策 Agent + 工具层" title="工单智能引擎" description="Work-Order Agent 按业务阶段完成意图识别与智能派单；状态流转与积分由确定性工具保证。"/><article className="agent-card cyan panel" style={{marginBottom:16}}><div className="agent-card-head"><span>1</span><Pill tone="success">{status}</Pill></div><h2>Work-Order Agent</h2><p>建单/富化：LLM + 规则分类与置信度 · 派单：技能/负载/距离/评分加权选人</p><div className="agent-stats"><div><small>本链路任务</small><b>{total}</b></div><div><small>待人审</small><b>{ops?.human_review_pending??0}</b></div></div></article><section className="panel"><div className="panel-title"><div><h2>确定性工具层</h2><p>不接入 LLM 的不变量</p></div></div><div className="role-features">{tools.map((item)=><span key={item}>✓ {item}</span>)}</div>{ops?.patrol_alerts?.length>0&&<div className="alert-card warning" style={{marginTop:12}}><span>!</span><div><strong>巡检告警</strong><p>{ops.patrol_alerts.join("；")}</p></div></div>}</section></div>;
}

function CreateModal({role,mode,close,done,fail}:{role:string;mode:UploadMode;close:()=>void;done:(data:State)=>void;fail:(text:string)=>void}){
  const picker=useRef<HTMLInputElement>(null);const [files,setFiles]=useState<File[]>([]),[busy,setBusy]=useState(false);
  const modeCopy={all:{title:"多模态报修",hint:"添加图片、语音或短视频",accept:"image/jpeg,image/png,image/webp,audio/mpeg,audio/wav,audio/mp4,audio/ogg,video/mp4,video/quicktime,video/webm"},image:{title:"图片报修",hint:"拍照或选择现场图片",accept:"image/jpeg,image/png,image/webp"},audio:{title:"语音报修",hint:"录音或选择语音文件",accept:"audio/mpeg,audio/wav,audio/mp4,audio/ogg"},video:{title:"视频报修",hint:"拍摄或选择现场视频",accept:"video/mp4,video/quicktime,video/webm"},text:{title:"文字报修",hint:"无需附件，填写问题后直接提交",accept:""}}[mode];
  const submit=async(event:FormEvent<HTMLFormElement>)=>{event.preventDefault();setBusy(true);try{const values=new FormData(event.currentTarget),attachmentIds:number[]=[];for(const file of files){const form=new FormData();form.append("file",file);const response=await fetch("/api/platform",{method:"POST",headers:{"x-workorder-role":role},body:form});const body=await response.json();if(!response.ok)throw new Error(`${file.name}：${body.error||"上传失败"}`);attachmentIds.push(body.id);}const response=await fetch("/api/platform",{method:"POST",headers:{"content-type":"application/json","x-workorder-role":role},body:JSON.stringify({action:"create",title:values.get("title"),description:values.get("description"),category:values.get("category"),priority:values.get("priority"),area:values.get("area"),attachmentIds})});const body=await response.json();if(!response.ok)throw new Error(body.error||"创建失败");done(body);}catch(error){fail(error instanceof Error?error.message:"提交失败");}finally{setBusy(false);}};
  return <div className="modal-backdrop" onMouseDown={(event)=>event.target===event.currentTarget&&close()}><form className="modal" onSubmit={submit}><div className="modal-head"><div><Pill tone="live">居民报修服务</Pill><h2>{modeCopy.title}</h2><p>提交后将自动识别、分类并进入调度流程。</p></div><button type="button" onClick={close}>×</button></div><label>问题标题<input className="form-input" name="title" placeholder="例如：A3地下车库排水泵异响" required minLength={2}/></label><label>详细描述<textarea name="description" placeholder="请说明位置、现象和影响范围" required/></label><div className="form-row"><label>分类<select name="category"><option value="">AI自动识别</option><option>设备故障</option><option>安全隐患</option><option>环境卫生</option><option>综合服务</option></select></label><label>紧急程度<select name="priority"><option>中</option><option>高</option><option>紧急</option><option>低</option></select></label></div><label>发生区域<select name="area"><option>全园区</option><option>中心区</option><option>东区 · A3</option><option>西区 · B2</option><option>北区 · 1号门</option><option>南区 · C1</option></select></label>{mode!=="text"&&<><input ref={picker} className="hidden-file" type="file" multiple accept={modeCopy.accept} capture={mode==="image"||mode==="video"?"environment":mode==="audio"?"user":undefined} onChange={(event)=>setFiles(Array.from(event.target.files||[]).slice(0,10))}/><div className={`upload-zone upload-${mode}`} onClick={()=>picker.current?.click()}><span>{mode==="image"?"▧":mode==="audio"?"♫":mode==="video"?"▶":"＋"}</span><div><b>{files.length?`已选择${files.length}个文件`:modeCopy.hint}</b><small>{files.length?files.map((file)=>file.name).join("、"):"可调用手机拍摄或录音，也可选择已有文件；单文件不超过50 MB"}</small></div><button type="button">{mode==="image"?"拍照/选图":mode==="audio"?"录音/选择":mode==="video"?"拍摄/选择":"选择文件"}</button></div></>}<div className="modal-actions"><button type="button" onClick={close}>取消</button><button className="primary" disabled={busy} type="submit">{busy?"上传并分析中…":"提交并启动AI分析"}</button></div></form></div>;
}
