from enum import StrEnum


class ErrorCode(StrEnum):
    VALIDATION_ERROR = "COMMON_400"
    UNAUTHORIZED = "AUTH_401"
    FORBIDDEN = "AUTH_403"
    NOT_FOUND = "COMMON_404"
    CONFLICT = "COMMON_409"
    RATE_LIMITED = "COMMON_429"
    WORK_ORDER_NOT_FOUND = "WORK_ORDER_404"
    INVALID_TRANSITION = "WORK_ORDER_409"
    NO_WORKER_AVAILABLE = "DISPATCH_409"
    INFRASTRUCTURE_UNAVAILABLE = "INFRA_503"
    INTERNAL_ERROR = "COMMON_500"
